$('#es').click(function(){
	$('#job').text('Ingeniero en Tecnologías de la Información');
	$('#skills').text('Habilidades');
	$('#language').text('Idiomas');
	$('#spanish').text('Español');
	$('#english').text('Ingles');
	$('#experience').text('Experiencia de  Trabajo');
	$('.business').text('Empresa: ');
	$('.projects').text('Proyectos Realizados:');
	$('#job2').text('Desarrollador Android');
	$('#date_job2').text('Julio 2017 - Octubre 2017');
	$('#project1_job2').text('Desarrollo de una Aplicación Android para Buscar Trabajo y Personal en línea.');
	$('#commentary1_job2').text('Actualmente en la Play Store con nombre Jhobie.');
	$('#project2_job2').text('Desarrollo de una Aplicación Android para el servicio de auto lavado a domicilio.');
	$('#commentary2_job2').text('Inconcluso');
	$('#job1').text('Desarrollador Web (PHP) y Android');
	$('#date_job1').text('Diciembre 2014 - Julio 2017');
	$('#project1_job1').text('Development and monitoring of a CRM system for the company.');
	$('#project2_job1').text('Desarrollo de una Aplicación Android para el sistema CRM.');
	$('#project3_job1').text('Desarrollo, diseño y maquetación de una pagina web para la empresa METFORJA.');
	$('#project4_job1').text('Desarrollo de una Aplicación Android para el control de obras y mantenimiento de la vía pública.');
	$('#project5_job1').text('Desarrollo y seguimiento de un Sistema Financiero.');
	$('#education').text('Educación');
	$('.school').text('Universidad Tecnológica de Huejotzingo.');
	$('#certificate2').text('Ingenieria en Tecnologías de la Información.');
	$('#certificate1').text('Técnico Superior Universitario en Tecnologías de la Información');
	$('#knowledge').text('Otros Conocimientos');
	//$('#social_media').text('Encuéntrame en las redes sociales.');
});

$('#en').click(function(){
	$('#job').text('Enginner in Information Technologies');
	$('#skills').text('Skills');
	$('#language').text('Language');
	$('#spanish').text('Spanish');
	$('#english').text('English');
	$('#experience').text('Work Experience');
	$('.business').text('Business: ');
	$('.projects').text('Fulfilled Projects:');
	$('#job2').text('Developer Android');
	$('#date_job2').text('July 2017 - October 2017');
	$('#project1_job2').text('Development of an Android application to search for work and personal online.');
	$('#commentary1_job2').text('Currently in the Play Store with name Jhobie.');
	$('#project2_job2').text('Development of an Android application for the home auto-wash service.');
	$('#commentary2_job2').text('Unfinished.');
	$('#job1').text('Developer Web(PHP) and Android');
	$('#date_job1').text('December 2014 - July 2017');
	$('#project1_job1').text('Development and monitoring of a CRM web system for the company.');
	$('#project2_job1').text('Development of an Android application for the CRM system.');
	$('#project3_job1').text('Development, design and layout of a web page for the company METFORJA.');
	$('#project4_job1').text('Development of an Android application for the control of works and maintenance of the public road.');
	$('#project5_job1').text('Development and monitoring of a financial system.');
	$('#education').text('Education');
	$('.school').text('Technological University of Huejotzingo.');
	$('#certificate2').text('Engineering in Information Technologies.');
	$('#certificate1').text('Senior University Technician in Information Technologies.');
	$('#knowledge').text('Other Knowledge');
	//$('#social_media').text('Find me on social media.');
});